### PR TITLE
minor glitches

### PR DESCRIPTION
**Pull request by temporaer**
- json import missing from two files in multiwoz svm
- run.py requires opencv, added to install instructions
- some version requirements could not be resolved by pip, loosened
  constraints to make it work

### CODE REVIEW

**Comment by ConvLab** [comment]
@temporaer  Thanks for the fixing! Could you point out what errors you encountered when running run.py without installing opencv? I did not see this issue before.

**Comment by temporaer** [comment]
I just reproduced, here's what I did:
```bash
$ conda create -n convlab2 python=3.6.5
$ conda activate convlab2
$ pip install -r requirements.txt
$ python run.py
```
this results in:
```
ModuleNotFoundError: No module named 'cv2'
```
caused by importing cv2 in `convlab/lib/util.py:17`.

**Comment by ConvLab** [comment]
@temporaer thank you!  Could you include the package in requirements.txt in the PR?

**Comment by ConvLab** [comment]
@temporaer  thanks!

**Pull request merged**
