### PR TITLE
add larl model

### PR DESCRIPTION
**Pull request by jincli**

### CODE REVIEW

**Comment by singhaki** [comment]
what does svdic.pkl contain?

**Comment by jincli** [comment]
@singhaki  It is a list of slot-value pairs for multiwoz dataset.

**Comment by singhaki** [comment]
@jincli can you provide your trained larl model for it as  i have trained from orignal larl repo and did not have any svdic.pkl

**Comment by jincli** [comment]
@singhaki  https://convlab.blob.core.windows.net/models/larl_model.zip

**Pull request merged**
